services:
  db:
    image: postgres:16-alpine
    container_name: my_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: TorchGraphQLAPI
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && npm run start"

  frontend:
    build: 
      context: ./frontend/torch-task-react 
    container_name: TorchFrontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      -  "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/graphql

volumes:
  db_data: